version: '3.3'
services:
    local-redis:
        container_name: local-redis
        image: redis:alpine
        restart: always
        ports:
            - 6379:6379
        volumes:
            - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
